upstream active {
    server stable:5000 weight=10;
    server stable:5000 weight=0;
}
server {
    listen 80;
    location / {
        proxy_pass http://active;
        proxy_set_header Host $host;
    }
}
